### ISSUE TITLE
DLNA support

### ISSUE THREAD

**Issue by renne** [AlbrechtL/rtl_dab_streamer#2]
Please add a UPNP/DLNA-server which regularly runs a scan for DAB(+) radio stations and publishes all available DAB(+) stations via UPNP/DLNA in the local network. This will allow any DLNA-renderer in the local network to play DAB(+) radio stations.

**Comment by AlbrechtL** [comment]
The development of rtl_dab_streamer is not active anymore. But you can check [welle.io](https://www.welle.io).
