### ISSUE TITLE
End of develoment?

### ISSUE THREAD

**Issue by keiem** [AlbrechtL/rtl_dab_streamer#3]
Hello,  I search a tool to stream a DAB stream, I tought this could do it, but I don't see how to compile it on linux.  Is this project on the end of development?
I now use your rtl_fm_streamer.  But as FM radio is end of live in Belgium, I search for another solution with Dab+.

**Comment by AlbrechtL** [comment]
Please take a look at https://github.com/AlbrechtL/welle.io. There you have two tools one with a GUI (welle-io) and one for streaming (welle-cli).
